[tool.pyright]
include = ["annovep", "bin/annovep", "scripts"]

typeCheckingMode = "strict"
# FIXME: Disabled until project is fully typed
reportUnnecessaryIsInstance = "none"

[tool.ruff]
target-version = "py37"

[tool.ruff.lint]

select = ["ALL"]

ignore = [
    "A003",   # Class attribute is shadowing a Python builtin
    "ARG",    # flake8-unused-arguments
    "C90",    # mccabe
    "COM812", # missing-trailing-comma
    "D",      # pydocstyle
    "EM101",  # raw-string-in-exception -- Exception must not use a string literal
    "EM102",  # f-string-in-exception -- Exception must not use an f-string literal
    "EM103",  # dot-format-in-exception -- Exception must not use a `.format` string
    "FIX",    # flake8-fixme
    "PTH",    # flake8-use-pathlib
    "S101",   # assert -- Use of assert detected
    "S603",   # subprocess-without-shell-equals-true
    "T20",    # flake8-print
    "TD",     # flake8-todos
    "TRY003", # raise-vanilla-args
    "TRY400", # error-instead-of-exception
    # Disabled due to too many false positives
    "ERA001",  # commented-out-code -- Found commented out code
    "PLR2004", # magic-value-comparison -- Magic value used in comparison
    "SIM115",  # open-file-with-context-handler
    # Disabled due to personal style preferences
    "PLW2901", # redefined-loop-name -- `for` loop variable `value` overwritten
    "RET505",  # superfluous-else-return -- Unnecessary `elif` after `return` statement
    "RET506",  # superfluous-else-raise -- Unnecessary `elif` after `raise` statement
    "RET507",  # superfluous-else-continue --Unnecessary `elif` after `continue`
    "RET508",  # superfluous-else-break -- Unnecessary `elif` after `break` statement
    # Disabled due to hits in non-performance critical code where manual is clearer
    "PERF401", # manual-list-comprehension -- Use a list comprehension
    # Disabled due to conflict with `format` command
    "ISC001", # single-line-implicit-string-concatenation
    # Complexity warnings disabled for now
    "PLR0904", # too-many-public-methods
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "PLR0916", # too-many-boolean-expressions
]
